# Generated by Django 6.0.6 on 2026-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('attendee', 'Attendee'), ('superadmin', 'Superadmin')], default='attendee', max_length=10),
        ),
    ]
