# Generated by Django 6.0.6 on 2026-06-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
    ]
